name: zad_aldaia
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+4

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  share_plus: ^11.0.0
  html_unescape: ^2.0.0
  intl: 0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  flutter_animate: ^4.5.2
  defer_pointer: ^0.0.2
  equatable: ^2.0.7
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.6
  cached_network_image: ^3.4.1
  youtube_player_iframe: ^5.2.1
  youtube_player_flutter: ^9.1.1
  path_provider: ^2.1.5
  external_path: ^2.2.0
  uuid: ^4.4.2
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  logger: ^2.4.0
  json_annotation: ^4.9.0
  image_downloader_web: ^2.0.6
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.0
  intro_screen_onboarding_flutter: ^1.0.0
  animations: ^2.0.11
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.1
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  file_picker: ^8.0.0+1
  rename: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/png/zad_logo.png
  adaptive_icon_background: "#052F47"
  adaptive_icon_foreground: assets/images/png/zad_logo.png
  min_sdk_android: 21


flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/
    - assets/images/flags/
    # - assets/images/
    - assets/images/png/
    # - assets/images/svg/
    - web/sqlite3.wasm
    - web/drift_worker.js



  fonts:
     - family: almarai_bold
       fonts:
         - asset: assets/fonts/almarai_bold.ttf
     - family: pin_icon
       fonts:
         - asset: assets/fonts/PinIcon.ttf
     - family: search_icon
       fonts:
         - asset: assets/fonts/search_icon.ttf
     - family: Exo 
       fonts:
         - asset: assets/fonts/Exo.ttf
     - family: Rubik 
       fonts:
         - asset: assets/fonts/Rubik.ttf 
     - family: Micro5 
       fonts:
         - asset: assets/fonts/Micro5.ttf
     - family: Jolly 
       fonts:
         - asset: assets/fonts/Jolly.ttf   
     - family: Protest 
       fonts:
         - asset: assets/fonts/Protest.ttf 
flutter_intl:
  enabled: true
